name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  applicationfolder: spring-boot-hello-world-example
  AWS_REGION: us-east-1
  S3BUCKET: my-unique-bucketfhfdfplel8

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout repository
         uses: actions/checkout@v2

       - name: List Directory
         run: ls -R /home/runner/work/GitActions/GitActions/

      #- name: Set up JDK 8
       # uses: actions/setup-java@v2
       # with:
       #   distribution: 'adopt'
        #  java-version: '8'

       - name: Set up JDK 11
         uses: actions/setup-java@v2
         with:
           distribution: 'adopt'
           java-version: '11'

       - name: Build with Maven
         run: mvn -X-B package --file ${{ github.workspace }}/spring-boot-hello-world-example/pom.xml
       
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      
       - name: Ensure target directory exists
         run: mkdir -p spring-boot-hello-world-example/target
  

       - name: Deploy to S3
         working-directory: ${{ env.applicationfolder }}/target
         #run: aws s3 cp *.war s3://${{ env.S3BUCKET }}/ --region ${{ env.AWS_REGION }}
         #run: aws s3 sync . s3://my-unique-bucketfhfdfplel8
        run: |
          aws s3 sync . s3://my-unique-bucketfhfdfplel8 
          <!-- --exclude '.git/*' --exclude '.github/*' -->
         
